meta_product_name: "Resort Runner"
meta_title: "Resort Runner - Sit back and enjoy your holiday, while we run things for you."
meta_description: "Resort Runner is a SaaS based platform aimed at streaming lining activities, customers service and increasing revenue."
meta_image: "cover.png"
